### ISSUE TITLE
Consider renaming function `charged` to `ischarged`, `radioactive` to `isradioactive` to better align with Julia's standard library's naming convention?

### ISSUE THREAD

**Issue by singularitti** [tmattick/ChemicalFormula.jl#5]
In Julia's std lib, when we want to return whether a condition is satisfied, the naming convention usually starts with `is`, e.g, `isone`, `iszero`, `isfinite`, `isexpr`, `isimmutable`, etc.

I supposed this convention also applies to the functions [`charged`](https://github.com/tmattick/ChemicalFormula.jl/blob/07c0be980f4b1911063b236bddf7ae108630da70/src/ChemicalFormula.jl#L215) and [`radioactive`](https://github.com/tmattick/ChemicalFormula.jl/blob/07c0be980f4b1911063b236bddf7ae108630da70/src/ChemicalFormula.jl#L204-L212), so could we rename them to `ischarged` and `is radioactive` in the next release?

**Comment by tmattick** [comment]
Thanks for the suggestion
