### ISSUE TITLE
Should `sumformula` and `hillformula` still return `Formula` types?

### ISSUE THREAD

**Issue by singularitti** [tmattick/ChemicalFormula.jl#7]
I generate some strings like "SiOO", and construct them `Formula`s, but then I find out that if I only use `sumformula`, it will give me a string:

```julia
julia> Formula("SiOO") |> sumformula
"SiO2"
```

If I want to operate on these things, I still need to convert them to `Formula` first:

```julia
julia> Formula("SiOO") |> sumformula |> Formula
Formula("SiO2", Dict{Symbol, Int32}(:Si => 1, :O => 2), 0, nothing)
```

This is a bit ugly. Could we still return `Formula` types in these methods?
The only thing you [changed is the `Formula.formula` field.](https://github.com/tmattick/ChemicalFormula.jl/blob/81df0bdd976598646890f406d192dc5df2eaa8b0/src/ChemicalFormula.jl#L59-L65)

If so, `sumformula` and `hillformula` could be renamed to `sumnotation` and `hillnotation`, etc., since they are more like a transform of the original `Formula` to a new `Formula`.

**Comment by tmattick** [comment]
To be honest, I don't see the benefit in working it this way. The reason intended for `sumformula` and `hillformula` is pretty printing. All operations on the formulae should be the same whether you use the summed version or not, e.g. 
```
julia> formulamass(Formula("SiO2")) == formulamass(Formula("SiOO"))
true
```
However, please let me know if there is any reason I can't see. In that case I will definitely consider making the edit.
